### ISSUE TITLE
MaxInt Error

### ISSUE THREAD

**Issue by Togame-san** [goulu/pdfminer#45]
Problem arises when you try to run pdf2txt. Error trace states can not import max int. I'm running Python 3.5.1. After researching the error, I've come to the conclusion that Python 3.x.x have removed the system constant maxint; hence, the inability to import said maxint. 
Um...
Please send aid.

**Comment by goulu** [comment]
You probably use the original pdfminer from euske or another fork, because this one (called pdfminer.six) was precisely written to circumvent such problems :-)

I just double checked and pdf2txt works fine with Python 3.5.2 here and the only occurence of maxint in the code is in the comment of the following line in utils.py:

    INF=2147483647 #from sys import maxint as INF #doesn't work anymore under Python3, but PDF still uses 32 bits ints
